version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 77M
        reservations:
          cpus: '0.01'
          memory: 30M

  whoami:
    image: jwilder/whoami
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=whoami.example
      - VIRTUAL_PORT=8000
    deploy:
      mode: replicated
      replicas: 2 # https://docs.docker.com/compose/compose-file/deploy/#replicas
      resources:  # https://docs.docker.com/compose/compose-file/compose-file-v3/#resources
        limits:
          cpus: '0.05'
          memory: 33M
        reservations:
          cpus: '0.01'
          memory: 6M

  my-blog:
    image: aaingyunii/aaingyunii.github.io:latest
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=member.blog.io
      - VIRTUAL_PORT=8000

  baam:
    image: baamboo/baamsoo.github.io:1.4.0
    expose:
      - "8001"
    environment:
      - VIRTUAL_HOST=abc.google.com
      - VIRTUAL_PORT=8001

  jiugnim:
    image:  jiugnim/sam1000wongithubio
    expose:
      - "8002"
    environment:
      - VIRTUAL_HOST=def.naver.com
      - VIRTUAL_PORT=8002

  minjung:
    image:  minjung818/minjung00.github.io:1.4.0
    expose:
      - "8003"
    environment:
      - VIRTUAL_HOST=ghi.daum.net
      - VIRTUAL_PORT=8003