version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 77M
        reservations:
          cpus: '0.01'
          memory: 30M

  whoami:
    image: jwilder/whoami
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=whoami.example
      - VIRTUAL_PORT=8000
    deploy:
      mode: replicated
      replicas: 1 # https://docs.docker.com/compose/compose-file/deploy/#replicas
      resources:  # https://docs.docker.com/compose/compose-file/compose-file-v3/#resources
        limits:
          cpus: '0.05'
          memory: 33M
        reservations:
          cpus: '0.01'
          memory: 6M

  my-blog:
    image: aaingyunii/aaingyunii.github.io:latest
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=api.aik.io
      - VIRTUAL_PORT=80

  baam:
    image: baamboo/baamsoo.github.io:1.4.0
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=abc.google.com
      - VIRTUAL_PORT=80

  jiugnim:
    image:  jiugnim/sam1000wongithubio
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=zxc.naver.com
      - VIRTUAL_PORT=80

  minjung:
    image:  minjung818/minjung00.github.io:1.4.0
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=kgb.cia.go.kr
      - VIRTUAL_PORT=80