# fly.toml app configuration file generated for homepage-aaingyunii on 2023-10-27T14:38:30+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "homepage-aaingyunii"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 3
  processes = ["app"]
